server/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.base import RedirectView
from tastypie.api import Api
from provserver.api import ContainerResource


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# Tasty Pie API configurations
v0_api = Api(api_name='v0')
v0_api.register(ContainerResource())

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # OAuth authentication
    url(r'^oauth/', include('oauth_provider.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^api/', include(v0_api.urls)),
    (r'^store/', include('provserver.urls')),
    (r'^$', RedirectView.as_view(url='/store')),
)

server/provserver/forms.py
from django.forms import ModelForm, Textarea, Form, CheckboxSelectMultiple
from django import forms
from models import UserProfile, Container, Submission, License
from django.contrib.auth.models import User
from oauth_provider.models import Consumer
from prov.model import ProvBundle
from django.utils.safestring import mark_safe
from urllib2 import URLError, urlopen
from json import loads
from django.core.mail import send_mail
from settings import ADMINS


class ProfileForm(ModelForm):
    ''' Form representing the UserProfile Model '''
    
    username = forms.CharField(label=("Username"), min_length=3)
    password = forms.CharField(label=("Password"), widget=forms.PasswordInput, min_length=3)
    confirm_password =  forms.CharField(label=("Confirm password"), widget=forms.PasswordInput, min_length=3)
    class Meta:
        model = UserProfile
        exclude = ('user')
        
    def clean(self):
        if 'username' in self.cleaned_data:
            if User.objects.filter(username=self.cleaned_data['username']).exists():
                raise forms.ValidationError(u'The username already exists.')
            
        if 'password' in self.cleaned_data and 'confirm_password' in self.cleaned_data:
            if self.cleaned_data['password'] != self.cleaned_data['confirm_password']:
                raise forms.ValidationError(u'Passwords did not match.')
        return self.cleaned_data
    
    def save(self, commit=True):
        if self.instance.pk is None:
            fail_message = 'created'
        else:
            fail_message = 'changed'
        if self.errors:
            raise ValueError("The %s could not be %s because the data didn't"
                         " validate." % ('UserProfile', fail_message))
        self.instance = User.objects.create_user(username=self.cleaned_data['username'], password=self.cleaned_data['password'])
        return self.instance
    
class AppForm(ModelForm):
    '''Form representing the Consumer Model for OAuth '''
    
    class Meta:
        model = Consumer
        fields = ('name', 'status', 'description')
        widgets ={'description': Textarea(attrs={'class': 'span6'}),}

class LicenseMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return mark_safe('<a href="{u}">{t}</a>'.format(t=obj.title, u=obj.url))

class BundleForm(Form):
    ''' Form for creating a Bundle '''
    
    rec_id = forms.CharField(label=('Bundle ID'))
    public = forms.BooleanField(label=('Public'), required = False)
    submission = forms.FileField(label=('Original File'), required = False)
    license = LicenseMultipleChoiceField(License.objects, widget=CheckboxSelectMultiple, required=False)
    url = forms.URLField(label='URL to the bundle file:', required=False)
    content = forms.CharField(label=('Content (in JSON format)'), widget=Textarea(attrs={'class': 'span7'}), required=False)
    
    def clean(self):
        self.bundle = ProvBundle()
        ''' Try to parse content or download and parse URL - one at least needed'''
        if self.cleaned_data['content']:
            try:
                self.bundle._decode_JSON_container(loads(self.cleaned_data['content']))
            except ValueError:
                raise forms.ValidationError(u'Wrong syntax in the JSON content.')
        elif self.cleaned_data['url']:
            try:
                source = urlopen(self.cleaned_data['url'], timeout=5)
                url_content = source.read()
                source.close()
            except URLError:
                raise forms.ValidationError(u'There was a problem accessing the URL.')
            try:
                self.bundle._decode_JSON_container(loads(url_content))
            except ValueError:
                raise forms.ValidationError(u'Wrong syntax in the JSON content at the URL.')
        else:
            raise forms.ValidationError(u'No content or URL provided.')
        return self.cleaned_data
    
    def save(self, owner, commit=True):
        if self.errors:
            raise ValueError("The %s could not be %s because the data didn't"
                         " validate." % ('Container', 'created'))
            
        container = Container.create(self.cleaned_data['rec_id'], self.bundle, owner, self.cleaned_data['public'])
        save = False
        
        if 'submission' in self.files:
            file_sub = self.files['submission']
            sub = Submission.objects.create()
            sub.content.save(sub.timestamp.strftime('%Y-%m-%d%H-%M-%S')+file_sub._name, file_sub)
            container.submission = sub
            save = True
            
        for l in self.cleaned_data['license']:
            container.license.add(l)
            save = True
            
        if save:
            container.save()
        return container
    
class SearchForm(Form):
    ''' Form for searching for a bundle '''
    name = forms.CharField(label=('Name'), required=False, 
                           widget=forms.TextInput(attrs={'class':'input-medium'}))
    id = forms.CharField(label=('Identifier'), required=False, 
                         widget=forms.TextInput(attrs={'class':'input-medium'}))
    literal = forms.CharField(label=('Literal'), required=False, 
                              widget=forms.TextInput(attrs={'class':'input-medium'}))
    value = forms.CharField(label=('Value'), required=False, 
                            widget=forms.TextInput(attrs={'class':'input-medium'}))
    any = forms.CharField(label=('Any Field'), required=False, 
                          widget=forms.TextInput(attrs={'class':'input-medium'}))
    start_time_date = forms.DateField(label=('Starting time'), required=False,
                                      widget=forms.TextInput(attrs={'class':'input-small',
                                                                    'readonly' : '' ,}))
    start_time_time = forms.TimeField(required=False,
                                      widget=forms.TextInput(attrs={'class':'timepicker-1 input-small',
                                                                    'readonly' : '' ,}))
    end_time_date = forms.DateField(label=('End time'), required=False,
                                      widget=forms.TextInput(attrs={'class':'input-small',
                                                                    'readonly' : '' ,}))
    end_time_time = forms.TimeField(required=False,
                                      widget=forms.TextInput(attrs={'class':'timepicker-1 input-small', 
                                                                    'readonly' : '' ,}))
    choice = forms.ChoiceField(required=True, choices = 
                               (('name', 'name'), ('id','id'), 
                                ('type', 'type'), ('time', 'time'),
                                ('any', 'any')))


class ContactForm(Form):
    subject = forms.CharField(label=('Subject'), required=True)
    message = forms.CharField(label=('Message'), required=True, widget=Textarea(attrs={'class': 'span5'}))
    sender = forms.EmailField(label=('Sender'), required=True)
    
    def save(self):
        ''' Sends an email to the ADMINS in settings.py'''
        if self.errors:
            raise ValueError("The %s could not be %s because the data didn't"
                         " validate." % ('Email', 'send'))
        send_mail(self.cleaned_data['subject'], self.cleaned_data['message'], 
                  self.cleaned_data['sender'], [a[1] for a in ADMINS])

server/templates/server/about.html
{# Copyright (C) 2011 University of Southampton #}
{% extends "base_clean.html" %}
{% load url from future %}
{% block title %}PROVServer: About{% endblock %}
{% block header %}<h1>About the Provenance Server</h1>{% endblock %}
{% block content %}
  <div class="span8">
	<p class="lead"> The Provenance Server is a web service that allows you to store, browse
	and manage your provenance bundles. The server can be accessed via this Web interface or via
	the REST API (using <a href="/store/help/apikey/">an API key</a> or
	<a href="/store/help/oauth/">OAuth authentication</a>).<p>
	<h2>Technology</h2>
	<p class="lead">This service was built upon the <a href="http://pypi.python.org/pypi/store">prov
	package</a>, which provides an Python implementation of the PROV specifications being standardised
	at the <a href="w3.org/2011/store/">	W3C Prov Working Group</a>. <br>
	The web server is built on <a href="http://www.djangoproject.com/">Django
	Web framework</a>.<p>
	<h2>Acknowledgements</h2>
	<p class="lead">The ProvPy package and this service are funded by an EPSRC grant (EP/H500243/1)
	and by the <a href="http://www.orchid.ac.uk">ORCHID Programme</a>.<p>
  </div>
{% endblock %}

server/templates/server/api_key_help.html
{# Copyright (C) 2011 University of Southampton #}
{% extends "base_nav.html" %}
{% load url from future %}
{% block title %}PROVServer: API Key Help{% endblock %}
{% block header %}<h1>Documentation: API Key</h1>{% endblock %}
{% block content %}
		<div id="Overview" class="anchorOffset"></div>
		<h3 id="Overview">API Overview</h3>
		<p>The Provenance Server's API provides a RESTful web service for
		storage and access of provenance bundles in JSON format as specified 
		<a href="http://users.ecs.soton.ac.uk/tdh/json/">here</a> 
		for the W3C's Provenance Data Model. Via the API, any client can manipulate bundles
		stored on a server and explore and retrieve information from other clients.
		</p>
		<div id="Authentication" class="anchorOffset"></div>
		<h3>API Key Authentication</h3>
		<p>The API supports Basic Http Authentication with user credential in the form of username and API Key.
		For this reason we suggest using the API Key Authentication only with a secured connection (i.e. https).
		The user credential is in the form of the username, chosen by the client at registration, 
		and an auto generated API key*. When you log in your account,
		you can view your API key by clicking on 'API Key' (on the top navigation bar). For security
		reasons, you can generate a new API key  in case the existing key
		has been compromised. 
		</br></br>
		* Note that the user credential here mentioned (username and API key) are not the same as 
		the credential used for this web page. The username is the same, but on registration the client
		creates his own separate password for accessing the server, which is different from the API key.
		</p>
		<div id="Usage" class="anchorOffset"></div>
		<h3>Basic Usage</h3>
		<p>The API supports all of the RESTful methods PUT/POST/GET/DELETE.
		You should query the server at the API
		url, which is in the following form: https://'domain'/'API url'/'resource name',
		where 'domain' is the domain address of the server(www.example.com),
		the API url is in the form 'api/vX' where X is version used(api/v0),
		the resource name is the Bundles name chosen by the service provider(account).
		The example url would form into 'https://www.example.com/api/v0/bundle'.
		This query would be to the list of all your bundles (by 'yours' is meant to which
		you have the appropriate permission dependable on the method type of the request).
		If you want to access a specific resource you should first acquire it's ID(12) and the 
		append it at the end of the url with a slash(/) in front:</br>
		https://www.example.com/api/v0/12</br>
		Every request should be correctly authenticated in order to receive the desired response.
		The Authentication is done as specified by the Basic Authentication portocol - setting 
		the 'Authorization' Header of the request with the correct credential. The format used is 
		'ApiKey username:key'. Note the first 'ApiKey' stands for the literal 'ApiKey' and it
		defines the type of authentication you are using. The user credentials are not hashed at all, 
		rather send in plain form.<br/>
		The only other requirement is that the data you send to the server to be in correct JSON
		form as specified by the RPOV-JSON documentation. 
		</p>
		<div id="Example" class="anchorOffset"></div>
		<h3>Examples</h3>
		<p>For this example let's assume you are a client with username 'patence' 
		and an API key 'b4702794b52445bab04a51ead73d5adbc554c970'. </br>
		The variable 'bundle' is assumed trough the examples to be any abstract object
		representation of a provenance bundle. Different languages and implementation 
		are possible, the only requirement is that it can be serialized accordingly.</br></br>
		If you want to add a new bundle to your account you should use the 'POST' method on the 
		resource list url. If the POST is successful the response will contain the new 
		bundle's information, including it's ID, and its location in a header.</p>
		<pre>
var user = 'patence';
var pass = 'b4702794b52445bab04a51ead73d5adbc554c970';
var tok = user + ':' + pass;
var auth = 'ApiKey ' + tok;</pre>
<div id="js" class="anchorOffset"></div>
<h3>JavaScript</h3> </p>
		<pre>
var request = new XMLHttpRequest();
request.setRequestHeader('Content Type', 'applicaton/json');
request.setRequestHeader('Authorization', auth);
// Create the callback:
request.onreadystatechange = function() {
	if (request.readyState != 4) return; // Not there yet
	if (request.status != 200) {
	// Handle request failure here...
	return;
	}
request.open('POST','https://www.example.com/api/v0/bundle/');
request.send();
// Request successful, read the response
var response = request.responseText;
// ... and use it as needed by your application</pre>
		<div id="ajax" class="anchorOffset"></div>
		<h3>Ajax</h3>
		<pre>
$.ajax({
	type: 'POST',
	url: 'https://www.example.com/api/v0/bundle/',
	data: JSON.stringify(bundle),
	contentType: 'application/json',
	beforeSend: function(req) {
		req.setRequestHeader('Authorization', auth);
	},
	success: function(data) {
		//do something with the data received
	}
});</pre>
		<div id="php" class="anchorOffset"></div>
		<h3>PHP</h3>
		<pre>
// Create Http context details
$contextData = array ( 
	'method' => 'POST',
	'header' => 
		"Connection: close\r\n".
		"Content-Length: ".strlen($bundle_serialized)."\r\n".
		"Content-Type: application/json\r\n".
		"Authorization: ".$auth."\r\n",
	'content'=> $bundle_serialized);
// Create context resource for our request
$context = stream_context_create (array ( 'http' => $contextData ));
// Read page rendered as result of your POST request
$result =  file_get_contents (
                  'https://www.example.com/api/v0/bundle/',false, $context);
// Server response is now stored in $result variable so you can process it
});</pre>
		<div id="Responses" class="anchorOffset"></div>
		<h3>API Responses</h3>
		<table class="table">  
	        <thead>  
	          <tr>
	          <th style="width:10%"><h5>Method</h3></th>
	          <th style="width:30%"><h5>Response Code</h3></th>
	          <th style="width:60%"><h5>Response Description</h3></th>
	          </tr>  
	        </thead>  
	        <tbody>
	        	<tr>
	        		<td>Any</td>
	        		<td>401 Unauthorized</h3>
	        		<td>There is a problem with the Authentication provided in the HTTP Header.</td>
	        	</tr>
	        	<tr>
	        		<td>Any</td>
	        		<td>403 Forbidden</h3>
	        		<td>You do not have the access permissions requested for the resource.</td>
	        	</tr>
	        	<tr>
	        		<td>Any</td>
	        		<td>404 Not Found</h3>
	        		<td>The resource/url you have requested does not exist.</td>
	        	</tr>
	        	<tr>
	        		<td>Any</td>
	        		<td>500 Internal Server Error</h3>
	        		<td>Something went wrong on the server. We are going to look in to it, 
	        		but you can mail us with the condition in which you met this code.</td>
	        	</tr>
	        	<tr>
	        		<td>POST</td>
	        		<td>405 Bad Request</h3>
	        		<td>A problem occurred while parsing the JSON. Check syntax.</td>
	        	</tr>
	        	<tr>
	        		<td>GET</td>
	        		<td>200 OK</h3>
	        		<td>The resource was successfully retrieved.</td>
	        	</tr>
	        	<tr>
	        		<td>POST</td>
	        		<td>201 Created</td>
	        		<td>The resource was successfully created. A detailed information 
	        		of the resource will be held in the body.</td>
	        	</tr>	
	        	<tr>
	        		<td>DELETE</td>
	        		<td>205 No Content</td>
	        		<td>The resource was successfully deleted.</td>
	        	</tr>
	        </tbody>
	    </table>
	    <p> *Note: If no 'Authorization' Header is provided 
	    in the request you will be treated as Anonymous User.</p>
{% endblock %}

{% block sidebar %}
<h2>Contents</h2>
<ul>
	<li><h5><a href="#Overview">Overview</a></h5></li>
	<li><h5><a href="#Authentication">API Key</a></h5></li>
	<li><h5><a href="#Usage">Basic Usage</a></h5></li>
	<li><h5><a href="#Example">Example</a></h5>
		<ul>
			<li><h5><a href="#js">Javascript</a></h5></li>
			<li><h5><a href="#ajax">Ajax</a></h5></li>
			<li><h5><a href="#php">PHP</a></h5></li>
		</ul>
	</li>
	<li><h5><a href="#Responses">API Responses</a></h5></li>
	<li><h5><a href="#top">Back to Top</a></h5></li>
</ul>
{% endblock %}

server/templates/server/contact.html
{# Copyright (C) 2011 University of Southampton #}
{% extends "base_clean.html" %}
{% load url from future %}
{% block title %}PROVServer: Contact us{% endblock %}
{% block header %}<h2 class="offset1">Contact us</h2>{% endblock %}
{% block content %}
<div class="row">
  <div class="offset1 span6">
    <form class="form-horizontal" action="{% url 'provserver.views.contact' %}" enctype="multipart/form-data" method="post">
      <legend>Your message</legend>
        {% csrf_token %}
        {% for field in form %}
        <div class="control-group{% if field.errors %} error{% endif %}">
          <label class="control-label" for="{{ field.html_name }}">{{ field.label }}</label>
          <div class="controls">
            {{ field }}
            {% if field.errors %}<span class="help-block">{{ field.errors }}</span>{% endif %}
          </div>
        </div>
      {% endfor %}
      <div class="form-actions">
        <button type="submit" class="btn btn-primary" value="Send"><i class="icon-share-alt icon-white"></i> Send</button>
      </div>
    </form>
  </div>
  <div class="offset1 span3">
	<p><span class="label label-inverse"><i class="icon-envelope icon-white"></i> Write to us</span></p>
	<address>
		<strong>Dr Trung Dong Huynh</strong><br/>
		Electronics and Computer Science<br/>
		University of Southampton<br/>
		Southampton<br/>
		SO17 1BJ<br/>
		United Kingdom<br/>
	</address>
  </div>
</div>
{% endblock %}

server/templates/server/dashboard.html
{# Copyright (C) 2011 University of Southampton #}
{% extends "base_clean.html" %}
{% load url from future %}
{% block title %}PROVServer: Home{% endblock %}
{% block header %}{% endblock %}
{% block content %}
<div class="offset1">
{% if user.is_authenticated %}
	<p class="lead">Welcome {{ user.username }}, this is your Provenance Repository!</p>
	<p><em>TODO: Stats about the users, Links to relevant sections</em></p>	
{% else %}
	<h2>Welcome to the Provenance Repository</h2>
	<p class="lead span8">You can use it to store, browse and manage your provenance bundles together with
	lots of other people. You can either register as a user or browse all public bundles to get
	a look and feel of how it is. If you need help or any information you can find it in the 
	help menu in the upper right corner. Have fun!<p>
{% endif %}
</div>
{% endblock %}

server/templates/server/list_bundles.html
{# Copyright (C) 2011 University of Southampton #}
{% extends "base_nav.html" %}
{% load url from future %}
{% load server_tags %}
{% block title %}PROVServer Bundles{% endblock %}
{% block head %}
    <link href="/static/datepicker.css" rel="stylesheet">
    <link href="/static/timepicker.css" rel="stylesheet">
{% endblock %}
{% block header %}<h1>Provenance Bundles</h1>{% endblock %}
{% block content %}
	<p class="lead">Showing bundles {{ bundles.start_index }} to {{ bundles.end_index }} out of total {{ bundles.paginator.count }} bundle{{ bundles.paginator.count|pluralize}}.</p>
    {% include "server/pagination.html" %}
	<table id="top" class="table">  
        <tbody>
         {% for b in bundles %}  
          <tr>   
            <td>
              <a href="{% url 'provserver.views.bundle_detail' b.id %}">{{ b.content.rec_id }}</a>
              {% if b.public %}<i class="icon-eye-open" title="Public"></i>{% else %}<i class="icon-lock" title="Private"></i>{% endif %}
          	  {% ifequal b.owner user %}<i class="icon-user" title="Owned by me"></i>{% endifequal %}
            </td>
            <td><a href="{% url 'provserver.views.bundle_svg' b.id %}" title="View SVG" target="_blank"><i class="icon-picture"></i> View SVG</a></td>  
            {% ifequal b.owner user %}<td>
              <a href="{% url 'provserver.views.admin_bundle' b.id %}"><i class="icon-pencil"></i> Edit Permissions</a>              
            </td>
            <form action="{% url 'provserver.views.bundle_detail' b.id%}" method="post" >
            	{% csrf_token %}
            	<td><button class="btn btn-small btn-danger" type="submit" value="Delete"><i class="icon-trash icon-white"></i> Delete</button></td>
            </form>
            {% else %}<td></td><td></td>{% endifequal %}
          </tr>  
        {% endfor %}
        </tbody>  
      </table>
  {% if bundles|length > 10 %}{% include "server/pagination.html" %}{% endif %}
{% endblock %}


{% block sidebar %}
{% if user.is_authenticated %}
<a class="btn btn-success" href="{% url 'provserver.views.create_bundle' %}"><i class="icon-plus icon-white"></i> Add New Bundle</a>
<br/>
{% endif %}
<h3>Filter by:</h3>
<div class="tabbable">
  <ul class="nav nav-tabs" id="filter_tab" style="margin-bottom: 10px">
    <li class="active"><a href="#name" data-toggle="tab">Name</a></li>
    <li ><a href="#id" data-toggle="tab">Id</a></li>
    <li><a href="#type" data-toggle="tab">Type</a></li>
    <li><a href="#time" data-toggle="tab">Time</a></li>
    <li><a href="#any" data-toggle="tab">Any</a></li>
  </ul>
  <div class="tab-content">
    <div id="name" class="tab-pane active">
      <form class="well-form" action="{% url 'provserver.views.list_bundles' %}?page=1" enctype="multipart/form-data" method="post">
		{% csrf_token %}
	  	{{ form.name.label_tag }}
	  	{{ form.name }}{{ form.name.errors }}
	  	<br/>
  		<button class="btn btn-primary" type="submit" name="choice" value="name"><i class="icon-filter icon-white"></i> Filter</button>
	  	<a class="btn pull-right" href="{% url 'provserver.views.list_bundles' %}"><i class="icon-refresh"></i> Reset</a>
	  </form>
	</div>
    <div id="id" class="tab-pane">
      <form class="well-form" action="{% url 'provserver.views.list_bundles' %}?page=1" enctype="multipart/form-data" method="post">
		{% csrf_token %}
		{{ form.id.label_tag }}
	  	{{ form.id }}{{ form.id.errors }}
	  	<br/>
  		<button class="btn btn-primary" type="submit" name="choice" value="id"><i class="icon-filter icon-white"></i> Filter</button>
	  	<a class="btn pull-right" href="{% url 'provserver.views.list_bundles' %}"><i class="icon-refresh"></i> Reset</a>
	  </form>
    </div>
    <div id="type" class="tab-pane">
      <form class="well-form" action="{% url 'provserver.views.list_bundles' %}?page=1" enctype="multipart/form-data" method="post">
		{% csrf_token %}
	  	{{ form.literal.label_tag }}
	  	{{ form.literal }}{{ form.literal.errors }}
	  	{{ form.value.label_tag }}
	  	{{ form.value }}{{ form.value.errors }}
	  	<br/>
  		<button class="btn btn-primary" type="submit" name="choice" value="type"><i class="icon-filter icon-white"></i> Filter</button>
	  	<a class="btn pull-right" href="{% url 'provserver.views.list_bundles' %}"><i class="icon-refresh"></i> Reset</a>
	  </form>
    </div>
    <div id="time" class="tab-pane">
      <form class="well-form" action="{% url 'provserver.views.list_bundles' %}?page=1" enctype="multipart/form-data" method="post">
		{% csrf_token %}
		<div class="control-group">
    	  {{ form.start_time_date.label_tag }}
		  <span class="input-append date" data-date-format="dd-mm-yyyy">
		  	{{ form.start_time_date }}<span class="add-on"><i class="icon-calendar"></i></span>{{ form.start_time_date.errors}}
		  </span>&nbsp;
	  	  <span class="input-append bootstrap-timepicker-component">
        	{{ form.start_time_time }}
        	<span class="add-on"><i class="icon-time"></i></span>{{ form.start_time_time.errors}}
          </span>
         </div>
         <div class="control-group">
          {{ form.end_time_date.label_tag }}
          <span class="input-append date" data-date-format="dd-mm-yyyy">
	  		{{ form.end_time_date }}<span class="add-on"><i class="icon-calendar"></i></span>{{ form.end_time_date.errors}}
	  	  </span>&nbsp;
	  	  <span class="input-append bootstrap-timepicker-component">
        	{{ form.end_time_time }}
        	<span class="add-on"><i class="icon-time"></i></span>{{ form.end_time_time.errors}}
          </span>
        </div>
	  	<br/>
  		<button class="btn btn-primary" type="submit" name="choice" value="time"><i class="icon-filter icon-white"></i> Filter</button>
	  	<a class="btn pull-right" href="{% url 'provserver.views.list_bundles' %}"><i class="icon-refresh"></i> Reset</a>
	  </form>
    </div>
    <div id="any" class="tab-pane">
      <form class="well-form" action="{% url 'provserver.views.list_bundles' %}?page=1" enctype="multipart/form-data" method="post">
		{% csrf_token %}
		{{ form.any.label_tag }}
	  	{{ form.any}}{{ form.any.errors }}
	  	<br/>
  		<button class="btn btn-primary" type="submit" name="choice" value="any"><i class="icon-filter icon-white"></i> Filter</button>
  		<a class="btn pull-right" href="{% url 'provserver.views.list_bundles' %}"><i class="icon-refresh"></i> Reset</a>
	  </form>
    </div>
  </div><!-- /.tab-content -->
</div><!-- /.tabbable -->
<br/>
{% endblock %}
{% block lastscripts %}
      <script type="text/javascript" src="/static/bootstrap/js/bootstrap-datepicker.js"></script>
      <script type="text/javascript" src="/static/bootstrap/js/bootstrap-timepicker.js"></script>
      <script>
		$(function(){
			$('#id_start_time_date').datepicker({
				autoclose: 'True',
			});
			$('#id_end_time_date').datepicker({
				autoclose: 'True',
			});
            $('#id_start_time_time').timepicker({
            	minuteStep: 1,
                showSeconds: true,
                showMeridian: false,
				defaultTime: '00:00:00',
			});
			$('#id_end_time_time').timepicker({
				minuteStep: 1,
                showSeconds: true,
                showMeridian: false,
				defaultTime: '23:59:59',
			});
			$('#filter_tab a:eq({{choice}})').tab('show');
		});
      </script>
{% endblock %}

server/templates/server/login.html
{# Copyright (C) 2011 University of Southampton #}
{% extends "base_clean.html" %}
{% load url from future %}
{% block title %}PROVServer Login{% endblock %}
{% block header %}<h2 class="offset3">Log in to the Provenance Server</h2>{% endblock %}
{% block content %}
<div class="offset3 span4">
	{%if form.errors %}
		<div class="label"><h5>The username and password did not match!</h5></div>
	{% endif %}
	  <form  class="well" method="post" action="{% url 'django.contrib.auth.views.login' %}" name="myform">
		{% csrf_token %}
		<div class="control-group">
			<label class="control-label" for="id_username">Username: </label>
			{{ form.username }}  

			<label class="control-label" for="id_password">Password: </label>
			{{ form.password }} 
		</div>
        <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Login</button>
        <a class="btn pull-right" href="{% url 'provserver.views.registration' %}?next={{ next }}"><i class="icon-pencil"></i> Register</a> 
		<input type="hidden" name="next" value="{{ next }}" />
	</form>
</div>
{% endblock %}