config/routes.rb
Provenance::Application.routes.draw do

  resources :data_provider_users do

    resources :downloaded_data, :except => [:edit, :create] do
      member do
        get :return_data
        get :generate_provenance
        get :download
        get :post_micropost
      end
    end

    member do
      get :update_data
      get :facebook_get_oauth_token
      get :login
    end

    collection do 
      get :twitter_oauth
      get :overall_prov    
      get :update_all      
    end
  end

  resources :data_providers

  devise_for :users 
  devise_scope :users do
    get "sign_in", :to => "devise/sessions#new"
  end

  resources :users  
  root :to => 'data_provider_users#index'

  match '*path' => redirect('/')

end

app/models/data_provider_user.rb
class DataProviderUser < ActiveRecord::Base
  attr_accessible :data_provider_id, :user_id,  :update_frequency, :uid

  validates :user_id, presence: true

  belongs_to :user
  belongs_to :data_provider
  has_many :downloaded_datum, :dependent => :destroy


#checks to see whether it's facebook
 def facebook?
  return self.data_provider.name == "Facebook"
 end

 def twitter?
 	return self.data_provider.name == "Twitter"
 end

 def micropost?
 	return self.data_provider.name == "Micropost"
 end


#The cron job calls this method which will update 
 def self.cron(time)

 	case time
	 	when "hourly"
	 		data_provider_users = DataProviderUser.where(update_frequency: "hourly")
	 	when "daily"
	 		data_provider_users = DataProviderUser.where(update_frequency: "daily")

	 	when "fortnightly"
	 		data_provider_users = DataProviderUser.where(update_frequency: "fortnightly")

	 	when "weekly"
	 		data_provider_users = DataProviderUser.where(update_frequency: "weekly")

	 	when "monthly"
	 		data_provider_users = DataProviderUser.where(update_frequency: "monthly")
 	end

 	if !data_provider_users.empty?

 		data_provider_users.each do |dpu|
 			downloaded_data = dpu.determine_update
 			downloaded_data.save
 			downloaded_data.generate_provenance(true)
 		end
 	end
 end

 def determine_update
 	if self.facebook?
 		return self.update_facebook
 	elsif self.twitter?
 		return self.update_twitter
 	elsif self.micropost?
 		return self.update_micropost
 	else
 		raise "error, not a data provider user option"
 	end
 end



 def update_twitter

 	Twitter.configure do |config|
 	  config.consumer_key = "fYuL73SIEuhw6kgNvs2hA"
 	  config.consumer_secret = "49ujIlgckdjJGbuKV8IafH9rKuvO6PlSCuxEVspd4"
 	  config.oauth_token = self.access_token
 	  config.oauth_token_secret = self.oauth_token_secret 
 	end
	
	#this parses the results 	 
 	json_results = Twitter.user.to_json
 	return DownloadedDatum.new(name: "Twitter", data: json_results, data_provider_user_id: self.id)
 end

 def update_facebook

 	options = { :access_token => self.access_token, :format => 'json' }
 	query = Fql.execute({
 		"query1" => 'SELECT status_id, message, time, uid FROM status WHERE uid ='+self.uid,
 		"query2" => 'SELECT first_name, last_name, profile_url, sex, pic_small, about_me, friend_count, inspirational_people, username FROM user WHERE uid ='+self.uid
 	}, options)
 	results = (query[0].values[1])[0].merge(query[1].values[1][0])


 	json_results = results.to_json
 	return DownloadedDatum.new(name: "Facebook", data: json_results, data_provider_user_id: self.id)

 end

 def update_micropost
 	require 'net/http'
 	uri = URI("http://localhost:3001/users/#{self.uid.to_s}/get_last_micropost")

 	response = Net::HTTP.get(uri)

 	return DownloadedDatum.new(name:"Micropost", data: response, data_provider_user_id: self.id)

 end

  
end

app/controllers/data_provider_users_controller.rb
class DataProviderUsersController < ApplicationController
  load_and_authorize_resource

  # GET /data_provider_users
  # GET /data_provider_users.json
  def index
    @data_provider_users = DataProviderUser.where(user_id: current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @data_provider_users }
    end
  end

  # GET /data_provider_users/1
  # GET /data_provider_users/1.json
  def show
    @data_provider_user = DataProviderUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @data_provider_user }
    end
  end

  # GET /data_provider_users/new
  # GET /data_provider_users/new.json
  def new
    @data_provider_user = DataProviderUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @data_provider_user }
    end
  end

  # GET /data_provider_users/1/edit
  def edit
    @data_provider_user = DataProviderUser.find(params[:id])
  end

  # POST /data_provider_users
  # POST /data_provider_users.json
  def create
    @data_provider_user = DataProviderUser.new(params[:data_provider_user])
    @data_provider_user.user_id = current_user.id #this associates the given data_provider_user with the user that's creating it.

    respond_to do |format|
      if @data_provider_user.save
        format.html { redirect_to login_data_provider_user_path(@data_provider_user), notice: 'Data provider user was successfully created.' }
        format.json { render json: @data_provider_user, status: :created, location: @data_provider_user }
      else
        format.html { render action: "new" }
        format.json { render json: @data_provider_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /data_provider_users/1
  # PUT /data_provider_users/1.json
  def update

    @data_provider_user = DataProviderUser.find(params[:id])

    respond_to do |format|
      if @data_provider_user.update_attributes(params[:data_provider_user])
        format.html { redirect_to @data_provider_user, notice: 'Data provider user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @data_provider_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_provider_users/1
  # DELETE /data_provider_users/1.json
  def destroy
    @data_provider_user = DataProviderUser.find(params[:id])
    @data_provider_user.destroy

    respond_to do |format|
      format.html { redirect_to data_provider_users_url }
      format.json { head :no_content }
    end
  end



  #this provides the login page
  #it renders the login page from the view.
  def login
    require 'TwitterOauth'
    @data_provider_user = DataProviderUser.find(params[:id])

    if @data_provider_user.twitter?

      @request_token = TwitterOauth.request_url

      @data_provider_user.access_token = @request_token.token
      @data_provider_user.oauth_token_secret = @request_token.secret
      
      if @data_provider_user.save!
        redirect_to @request_token.authorize_url              
      end      

    end
  end

  def twitter_oauth
    require 'TwitterOauth'

    @data_provider_user = current_user.data_provider_users.last

    request_token = TwitterOauth.request_token(@data_provider_user.access_token, @data_provider_user.oauth_token_secret)
    
    @access_token = request_token.get_access_token(:oauth_verifier =>  params[:oauth_verifier] )

    if !@access_token.nil?
      @data_provider_user.access_token = @access_token.token
      @data_provider_user.oauth_token_secret = @access_token.secret
    else
      raise "Access Token Nil"
    end
    respond_to do |format|
      if @data_provider_user.save
        format.html { redirect_to data_provider_users_path, notice: 'Data provider user was successfully created.' }
        format.json { render json: @data_provider_user, status: :created, location: @data_provider_user }
      else
        format.html { render action: "new" }
        format.json { render json: @data_provider_user.errors, status: :unprocessable_entity }
      end
    end
  end


  #this method receives the update frequency and sets it for the cron job
  def update_frequency
    @data_provider_user = DataProviderUser.find(params[:id])
  end



  def update_data

    @data_provider_user = DataProviderUser.find(params[:id])
   

    @downloaded_datum = @data_provider_user.determine_update


    respond_to do |format|
      if @downloaded_datum.save
        format.html { redirect_to generate_provenance_data_provider_user_downloaded_datum_path(@data_provider_user.id, @downloaded_datum.id), notice: 'Downloaded datum was successfully created.' }
        format.json { render json: @downloaded_datum, status: :created, location: @downloaded_datum }
      else
        format.html { render action: "new" }
        format.json { render json: @downloaded_datum.errors, status: :unprocessable_entity }
      end
    end   
  end


#this gets the initial access token (is it really oauth??) and extends it for 60 days.
  def facebook_get_oauth_token

    require 'net/http'
    require 'uri'

    uri = URI.parse("https://graph.facebook.com/oauth/access_token")

    if !params[:access_token].nil?
    param = {'grant_type'=> 'fb_exchange_token', 'client_id' =>'308769445890556', 'client_secret'=>'acf570bff4de2f66da870a58d8116f47', 'fb_exchange_token'=> params[:access_token]}
    else
      raise "Access Token nil"
    end
    
    http = Net::HTTP.new(uri.host, uri.port) 
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(uri.path) 
    request.set_form_data( param )

    # instantiate a new Request object
    request = Net::HTTP::Get.new( uri.path+ '?' + request.body ) 

    response = http.request(request)
    token = response.body.match(/=(.*)&e/)[1]

    @data_provider_user = DataProviderUser.find(params[:id])
    if !params[:uid].nil?
      @data_provider_user.uid = params[:uid]
    else
      raise "UID nil"
    end
    @data_provider_user.access_token = token
    @data_provider_user.save


    respond_to do |format|
      format.html { redirect_to data_provider_users_url }
      format.json { head :no_content }
    end
  end


  #this gets the overall provenance of the system, collates it into one bundle and sends it to the prov server
  def overall_prov
    url = current_user.overall_prov

    respond_to do |format| 
      if !url.nil?
        format.html {redirect_to url }
        format.json { head :no_content }
      else
      format.html { redirect_to data_provider_users_url }
      format.json { head :no_content }
    end
    end
  end


  def update_all
    @dpus = current_user.data_provider_users

    @dpus.each do |dpu|

      downloaded_data = dpu.determine_update
      downloaded_data.save
      downloaded_data.generate_provenance(false)
    end

    respond_to do |format|
      format.html {redirect_to root_path}
      format.json { render json: @data_provider_users }
    end
  end

end

app/helpers/data_provider_users_helper.rb
module DataProviderUsersHelper

	def update_link(dpu)

		#if the dataprovider user is facebook return that code
		if(dpu.facebook? or dpu.twitter?)
			return "<td><a href=\"/data_provider_users/#{dpu.id.to_s}/update_data\">Update</a></td>".html_safe
		end
	end


	def last_updated_time(dpu)

	    if !dpu.downloaded_datum.blank?
	    	return "<td> #{dpu.downloaded_datum.last.updated_at} </td>".html_safe
	    else
	    	return '<td>N/A</td>'.html_safe
	    end
	end



end

app/views/data_provider_users/_form.html.erb
<%= form_for(@data_provider_user) do |f| %>
  <% if @data_provider_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_provider_user.errors.count, "error") %> prohibited this data_provider_user from being saved:</h2>

      <ul>
      <% @data_provider_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :data_provider_id %><br />
    <%= f.collection_select(:data_provider_id, DataProvider.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :update_frequency %>
    <%= f.select :update_frequency, [['None','None'],['hourly','hourly'], ['daily','daily'],['weekly','weekly'],['fortnightly', 'fortnightly'],['monthly','monthly']], :selected => @data_provider_user.update_frequency %>
  </div>
  <div class="actions">
    <%= f.submit nil, :class => 'btn' %>
  </div>
<% end %>

app/views/data_provider_users/_micropost.html.erb
<%= form_for(@data_provider_user, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @data_provider_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_provider_user.errors.count, "error") %> prohibited this data_provider_user from being saved:</h2>

      <ul>
      <% @data_provider_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="control-group">
    <%= f.label :uid, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :uid %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit nil, :class => 'btn' %>
  </div>
<% end %>

app/views/data_provider_users/edit.html.erb
<h1>Editing data_provider_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_provider_user %> |
<%= link_to 'Back', data_provider_users_path %>

app/views/data_provider_users/index.html.erb
<h1>Provenance Data Repository</h1>

Welcome, this is your personal data repository
<br/>
<br/>

 


<table class="table">
  <tr>
    <th>Data provider</th>
    <th>Last Updated </th>
    <th>Update Frequency</th>
    <th></th>
    <th></th>
    <th/>
    <th></th>
  </tr>

<% @data_provider_users.each do |data_provider_user| %>
  <tr>
    <td><%= data_provider_user.data_provider.name %></td>
    <%= last_updated_time(data_provider_user) %>
    <td><%= data_provider_user.update_frequency %></td>
    <td> <%= link_to 'View Data', data_provider_user_downloaded_data_path(data_provider_user)%> </td>
    <td> <%= link_to 'Update', update_data_data_provider_user_path(data_provider_user)%> </td>
    <td><%= link_to 'Edit', edit_data_provider_user_path(data_provider_user) %></td>
    <td><%= link_to 'Destroy', data_provider_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Data provider user', new_data_provider_user_path %> |
<%= link_to 'Overall Prov', overall_prov_data_provider_users_path %> |
<%= link_to 'Update All', update_all_data_provider_users_path%>

app/views/data_provider_users/login.html.erb
<% if @data_provider_user.facebook? %>
<div id="fb-root"></div> 

<script type="text/javascript">
$(document).ready(function(){ 
    facebook()
});

function facebook(){
      var button;
      var userInfo;
      
      window.fbAsyncInit = function() {
          FB.init({ appId: '308769445890556', //change the appId to your appId
              status: true, 
              cookie: true,
              xfbml: true,
              oauth: true});

         // showLoader(true);
         
         function updateButton(response) {
              button       =   document.getElementById('fb-auth');
              userInfo     =   document.getElementById('user-info');
              
              if (response.authResponse) {
                  //user is already logged in and connected
                  FB.api('/me', function(info) {
                      login(response, info);
                  });
                  
                  button.onclick = function() {
                      FB.logout(function(response) {
                          logout(response);
                      });
                  };
              } else {
                  //user is not connected to your app or logged out
                  button.innerHTML = 'Login';
                  button.onclick = function() {
                      FB.login(function(response) {
                          if (response.authResponse) {
                              FB.api('/me', function(info) {
                                  login(response, info);
                              });    
                          } else {
                              //user cancelled login or did not grant authorization
                          }
                      }, {scope:'email,user_birthday,status_update,publish_stream,user_about_me,read_stream,export_stream'});   
                  }
              }
          }
          
          // run once with current status and whenever the status changes
          FB.getLoginStatus(updateButton);
          FB.Event.subscribe('auth.statusChange', updateButton);  
      };
      (function() {
          var e = document.createElement('script'); e.async = true;
          e.src = document.location.protocol 
              + '//connect.facebook.net/en_US/all.js';
          document.getElementById('fb-root').appendChild(e);
      }());
      
      
      function login(response, info){
          if (response.authResponse) {
              var accessToken=   response.authResponse.accessToken;
              userInfo.innerHTML= '<img src="https://graph.facebook.com/' + info.id + '/picture">' + info.name + "<br /> Your Access Token: " + accessToken;
              button.innerHTML = 'Logout';

              $.ajax({
                url: '/data_provider_users/'+location.pathname.match(/\/data_provider_users\/(\d+)/)[1]
+'/facebook_get_oauth_token?access_token='+ accessToken+"&uid="+info.id,
                dataType: 'html',
                success: function(data){
                  // Somehow change this because VERY HACKY
                  document.location.href='/';
                },
                error: function(data){
                  // console.log("ERROR");
                },
              });
          }
      }

      function logout(response){
          userInfo.innerHTML                             =   "";
          document.getElementById('debug').innerHTML     =   "";
      }

}
</script>

<h3>Facebook</h3>
<br/>
<button id="fb-auth" class='btn btn-primary'>Login</button>
<br />
<div id="user-info"></div>
<br />
<div id="debug"></div>

<% elsif @data_provider_user.twitter? %>

<h3>Twitter</h3>

<%#debugger%>

<% elsif @data_provider_user.micropost? %>

<h3> Micropost </h3>
</br>

Enter your User ID shown on the home page.
<p/>

<%= render 'micropost' %>


<%end%>

app/views/data_provider_users/new.html.erb
<h1>New Data Provider User</h1>

<%= render 'form' %>

<%= link_to 'Back', data_provider_users_path %>

app/views/data_provider_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @data_provider_user.user_id %>
</p>

<p>
  <b>Data provider:</b>
  <%= @data_provider_user.data_provider_id %>
</p>

<p>
  <b>Update Frequency:</b>
  <%= @data_provider_user.update_frequency %>
</p>


<%= link_to 'Edit', edit_data_provider_user_path(@data_provider_user) %> |
<%= link_to 'Back', data_provider_users_path %>