config/routes.rb
Provenance::Application.routes.draw do

  resources :data_provider_users do

    resources :downloaded_data, :except => [:edit, :create] do
      member do
        get :return_data
        get :generate_provenance
        get :download
        get :post_micropost
      end
    end

    member do
      get :update_data
      get :facebook_get_oauth_token
      get :login
    end

    collection do 
      get :twitter_oauth
      get :overall_prov    
      get :update_all      
    end
  end

  resources :data_providers

  devise_for :users 
  devise_scope :users do
    get "sign_in", :to => "devise/sessions#new"
  end

  resources :users  
  root :to => 'data_provider_users#index'

  match '*path' => redirect('/')

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  validates :first_name, :last_name, :prov_username, :prov_access_token, :presence => true

  has_many :data_provider_users

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :prov_username, :prov_access_token



  def overall_prov
    require 'ProvRequests'
    require 'json'
    require 'active_support/core_ext/hash/deep_merge'

    prov = {}
  	@dpu = self.data_provider_users

  	@dpu.each do |dpu|
  		if !dpu.downloaded_datum.blank?
  			request = ProvRequests.get_request(self.prov_username, self.prov_access_token, dpu.downloaded_datum.last.prov_id)
  			results = ActiveSupport::JSON.decode(request)["prov_json"]
  			prov = prov.deep_merge(results)
  		end
  	end

  	if !prov.blank?
  		response = ProvRequests.post_request(self.prov_username, self.prov_access_token, prov, "Complete Prov")
  		prov_id = ActiveSupport::JSON.decode(response)["id"]
  		# debugger	
  		return "#{ENV['PROV_SERVER']}/store/bundles/#{prov_id}"
  	else	
  		return nil
  	end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource


  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: "form-horizontal"} ) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :first_name, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :first_name %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :last_name, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :last_name %><br/>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :email %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :prov_username, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :prov_username %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :prov_access_token, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :prov_access_token %>
    </div>
  </div>


  <div class="control-group">
    <div class="controls">
      <%= f.submit 'Create User', class: "btn" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table">
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path, class: "btn" %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Prov Username:</b>
  <%= @user.prov_username %>
</p>

<p>
  <b>Prov Access Token:</b>
  <%= @user.prov_access_token %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>