config/routes.rb
Provenance::Application.routes.draw do

  resources :data_provider_users do

    resources :downloaded_data, :except => [:edit, :create] do
      member do
        get :return_data
        get :generate_provenance
        get :download
        get :post_micropost
      end
    end

    member do
      get :update_data
      get :facebook_get_oauth_token
      get :login
    end

    collection do 
      get :twitter_oauth
      get :overall_prov    
      get :update_all      
    end
  end

  resources :data_providers

  devise_for :users 
  devise_scope :users do
    get "sign_in", :to => "devise/sessions#new"
  end

  resources :users  
  root :to => 'data_provider_users#index'

  match '*path' => redirect('/')

end

app/controllers/downloaded_data_controller.rb
class DownloadedDataController < ApplicationController
  load_and_authorize_resource

  # load_and_authorize_resource :data_provider_user
  # load_and_authorize_resource :downloaded_data, :through => :data_provider_user

  # GET /downloaded_data
  # GET /downloaded_data.json
  def index
    @downloaded_data = DownloadedDatum.where(data_provider_user_id: params[:data_provider_user_id]).order("updated_at DESC").page(params[:page]).per(10)
    @all_downloaded_data =  DownloadedDatum.where(data_provider_user_id: params[:data_provider_user_id])
    @data_provider_user = DataProviderUser.find(params[:data_provider_user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @downloaded_data }
    end
  end

  # GET /downloaded_data/1
  # GET /downloaded_data/1.json
  def show
    @downloaded_datum = DownloadedDatum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @downloaded_datum }
    end
  end

  # GET /downloaded_data/new
  # GET /downloaded_data/new.json
  def new
    @downloaded_datum = DownloadedDatum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @downloaded_datum }
    end
  end


  # PUT /downloaded_data/1
  # PUT /downloaded_data/1.json
  def update
    @downloaded_datum = DownloadedDatum.find(params[:id])

    respond_to do |format|
      if @downloaded_datum.update_attributes(params[:downloaded_datum])
        format.html { redirect_to @downloaded_datum, notice: 'Downloaded datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.json { render json: @downloaded_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /downloaded_data/1
  # DELETE /downloaded_data/1.json
  def destroy
    @downloaded_datum = DownloadedDatum.find(params[:id])
    @downloaded_datum.destroy

    respond_to do |format|
      format.html { redirect_to data_provider_user_downloaded_data_url }
      format.json { head :no_content }
    end
  end

  #this downloads the data to the user
  def download
    require 'active_support/core_ext/hash/deep_merge'

    @downloaded_datum = DownloadedDatum.find(params[:id])

    prov = {"has_provenance"=>"#{ENV['PROV_SERVER']}/store/bundles/#{@downloaded_datum.prov_id}"}

    data = ActiveSupport::JSON.decode(@downloaded_datum.data).deep_merge(prov)

    send_data data.to_json,
      :type => 'text',
      :disposition => "attachment; filename=#{@downloaded_datum.data_provider_user.data_provider.name+Time.now.to_s}.txt"
  end



  #this generates the provenance for downloaded data
  def generate_provenance
    @downloaded_datum = DownloadedDatum.find(params[:id])
    @downloaded_datum.generate_provenance(false)

    respond_to do |format|
      format.html { redirect_to data_provider_user_downloaded_datum_path(params[:data_provider_user_id], @downloaded_datum.id), notice: 'Downloaded datum was successfully created.' }
      format.json { render json: @downloaded_datum, status: :created, location: @downloaded_datum }
    end   
  end




  #this method is used to get data from the database.
  #this is done so that the JSON diff can retrieve the data and compare it
  def return_data
    @downloaded_datum = DownloadedDatum.find(params[:id])

    respond_to do |format|
      format.json { render json: @downloaded_datum.data}
    end
  end


  def post_micropost


    @downloaded_datum = DownloadedDatum.find(params[:id])
    @data_provider_user = DataProviderUser.find(params[:data_provider_user_id])

    if !@downloaded_datum.prov_id.blank?
      content = "Post made from Web app, Downloaded Data number #{@downloaded_datum.id}"
      has_provenance = ENV['PROV_SERVER']+"/store/bundles/"+@downloaded_datum.prov_id.to_s+".provn"

      require 'net/http'
      uri = URI("http://localhost:3001/users/#{@data_provider_user.uid.to_s}/remote_posting")

      params = {'content' => "Post made from Web app, Downloaded Data number #{@downloaded_datum.id}", 'has_provenance' => has_provenance, 'in_reply_to' => ActiveSupport::JSON.decode(@downloaded_datum.data)['data']['id'], 'bundle_number' => @downloaded_datum.id }

      http = Net::HTTP.new(uri.host, uri.port) 
      request = Net::HTTP::Get.new(uri.path) 

      request.set_form_data( params )

      response = http.request(request)

      respond_to do |format|
        format.html { redirect_to data_provider_user_downloaded_datum_path(@data_provider_user.id, @downloaded_datum.id)}
        format.json { render json: @downloaded_datum, status: :created, location: @downloaded_datum }
      end
    end
  end


end

app/helpers/downloaded_data_helper.rb
module DownloadedDataHelper

	def prov(dd)
		return "<link rel=\"http://www.w3.org/ns/prov#hasProvenance\" href=\"#{ENV['PROV_SERVER']}/store/bundles/#{dd.prov_id}.provn\">
		<link rel=\"http://www.w3.org/ns/prov#hasAnchor\" href=\"target-URI\">
		<meta name=\"green-turtle-rdfa-message\">".html_safe
	end

	def display_microlink(dd)

		if dd.data_provider_user.micropost? 
			ActionController::Base.helpers.link_to('Post Micropost', post_micropost_data_provider_user_downloaded_datum_path(dd.data_provider_user.id, dd)) + " |"
		end
	end



end

app/views/downloaded_data/_form.html.erb
<%= form_for(@downloaded_datum) do |f| %>
  <% if @downloaded_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@downloaded_datum.errors.count, "error") %> prohibited this downloaded_datum from being saved:</h2>

      <ul>
      <% @downloaded_datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/downloaded_data/index.html.erb
<%= stylesheet_link_tag 'jsondiffpatch.html.css' %>
<script type="text/javascript">


$(document).ready(function(){ 

  if($('#myvisualdiffcontainer').length >0){
    //global intentionally
    dataProviderID = location.pathname.match(/\/data_provider_users\/(\d+)/)[1]

    // console.log(dataProviderID)

    $.ajax({
      url: '/data_provider_users/'+dataProviderID+'/downloaded_data/'+$('#id_data').val()+'/return_data',
      dataType: 'html',
      success: function(data){
        json1 = JSON.parse(data);



        $.ajax({
          url: '/data_provider_users/'+dataProviderID+'/downloaded_data/'+$('#id_updated_at').val()+'/return_data',
          dataType: 'html',
          success: function(data){
            json2 = JSON.parse(data);


            //this displays the pretty json diff
            var d = jsondiffpatch.diff(json1, json2);
            //i.e. if there is a diff
            if(d != undefined){
              $('#myvisualdiffcontainer').empty().append(jsondiffpatch.html.diffToHtml(json1, json2, d));
            }
            else{
              $('#myvisualdiffcontainer').empty().append("There is no difference");
            }



          },
          error: function(data){
            console.log("ERROR");
          },
        });



      },
      error: function(data){
        console.log("ERROR");
      },
    });



    $('#id_updated_at').change(function(){
      $.ajax({
        url: '/data_provider_users/'+dataProviderID+'/downloaded_data/'+$('#id_updated_at').val()+'/return_data',
        dataType: 'html',
        success: function(data){
          json2 = JSON.parse(data);
          //this displays the pretty json diff
          var d = jsondiffpatch.diff(json1, json2);
          //i.e. if there is a diff
          if(d != undefined){
            $('#myvisualdiffcontainer').empty().append(jsondiffpatch.html.diffToHtml(json1, json2, d));
          }
          else{
            $('#myvisualdiffcontainer').empty().append("There is no difference");
          }
        },
        error: function(data){
          console.log("ERROR");
        },
      });  
    });


    $('#id_data').change(function(){
      $.ajax({
        url: '/data_provider_users/'+dataProviderID+'/downloaded_data/'+$('#id_data').val()+'/return_data',
        dataType: 'html',
        success: function(data){
          json1 = JSON.parse(data);
          //this displays the pretty json diff
          var d = jsondiffpatch.diff(json1, json2);
          //i.e. if there is a diff
          if(d != undefined){
            $('#myvisualdiffcontainer').empty().append(jsondiffpatch.html.diffToHtml(json1, json2, d));
          }
          else{
            $('#myvisualdiffcontainer').empty().append("There is no difference");
          }
        },
        error: function(data){
          console.log("ERROR");
        },
      });  
    });
  }

});

</script>

<h1>Listing Downloaded Data</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <!-- <th>Data</th> -->
    <th>Last Updated At</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @downloaded_data.each do |downloaded_datum| %>
  <% if can? :show, downloaded_datum %>
  <tr>
    <td><%= downloaded_datum.name %></td>
    <!-- <td><%= downloaded_datum.data %></td> -->
    <td><%= downloaded_datum.updated_at %></td>
    <td><%= link_to 'Download', download_data_provider_user_downloaded_datum_path(downloaded_datum.data_provider_user.id, downloaded_datum.id)%></td>
    <td><%= link_to 'Show', data_provider_user_downloaded_datum_path(downloaded_datum.data_provider_user.id, downloaded_datum.id) %></td>
    <td><%= link_to 'Destroy', [downloaded_datum.data_provider_user, downloaded_datum], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <%end%>

<% end %>
</table>
<%= paginate @downloaded_data %>

<br />


<%= link_to 'Update', update_data_data_provider_user_path(@data_provider_user)%>

<!-- <h3> Update frequency </h3> -->

<%#= collection_select(@data_provider_user) %>

<%unless @downloaded_data.blank? %>
<% if can? :show, @downloaded_data.first %>

<p/>
<h3> JSON Diff </h3>
<p/>
<br/>


<h4> New </h4>
<%= collection_select(:id, :updated_at, @all_downloaded_data.order('updated_at DESC'), :id, :updated_at ) %>
<p/>
<h4> Old </h4>
<%= collection_select(:id, :data, @all_downloaded_data.order('updated_at DESC'), :id, :updated_at ) %>

<div id="myvisualdiffcontainer"></div>
<%else%>
<script type="text/javascript">
  window.location.href="/"  // put your correct path in a string here
</script>  
<%end%>
<%end%>

app/views/downloaded_data/new.html.erb
<h1>New downloaded_datum</h1>

<%= render 'form' %>

<%= link_to 'Back', downloaded_data_path %>

app/views/downloaded_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @downloaded_datum.name %>
</p>

<p>
  <b>Data:</b>
  <%= @downloaded_datum.data %>
</p>



    <%= link_to 'View SVG', "#{ENV['PROV_SERVER']}/store/bundles/#{@downloaded_datum.prov_id}.svg" %> |
    <%= link_to 'Explicit Provenance Link', "#{ENV['PROV_SERVER']}/store/bundles/#{@downloaded_datum.prov_id}" %> |
    <%= display_microlink(@downloaded_datum) %>
    <%= link_to 'Back', data_provider_user_downloaded_data_path %>